spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3316/terminal_community?serverTimezone=Asia/Seoul
    password: 'Qwer1031!!'
  jpa:
    properties:
      hibernate:
        "[format_sql]": 'true' #sql 가독성 좋게 보여줌
        "[show_sql]": 'true' #만들어진 SQL 보여줌
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create #db 초기화 전략. 기존 테이블 삭제 후 생성 -> update 변경하면 삭제안함